//Global Textdraws:

new Text:Textdraw0;
new Text:Textdraw1;
new Text:Textdraw2;
new Text:Textdraw3;
new Text:Textdraw4;
new Text:Textdraw5;
new Text:Textdraw6;
new Text:Textdraw7;
new Text:Textdraw8;
new Text:Textdraw9;
new Text:Textdraw10;
new Text:Textdraw11;
new Text:Textdraw12;
new Text:Textdraw13;
new Text:Textdraw14;
new Text:Textdraw15;
new Text:Textdraw16;
new Text:Textdraw17;
new Text:Textdraw18;
new Text:Textdraw19;
new Text:Textdraw20;
new Text:Textdraw21;
new Text:Textdraw22;
new Text:Textdraw23;
new Text:Textdraw24;
new Text:Textdraw25;
new Text:Textdraw26;
new Text:Textdraw27;
new Text:Textdraw28;
new Text:Textdraw29;
new Text:Textdraw30;
new Text:Textdraw31;
new Text:Textdraw32;
new Text:Textdraw33;
new Text:Textdraw34;
new Text:Textdraw35;
new Text:Textdraw36;
new Text:Textdraw37;
new Text:Textdraw38;
new Text:Textdraw39;
new Text:Textdraw40;
new Text:Textdraw41;
new Text:Textdraw42;


Textdraw0 = TextDrawCreate(0.000000, 0.000000, "LD_SPAC:white");
TextDrawLetterSize(Textdraw0, 0.000000, 0.000000);
TextDrawTextSize(Textdraw0, 640.000000, 448.000000);
TextDrawAlignment(Textdraw0, 1);
TextDrawColor(Textdraw0, 7602175);
TextDrawSetShadow(Textdraw0, 0);
TextDrawSetOutline(Textdraw0, 0);
TextDrawFont(Textdraw0, 4);

Textdraw1 = TextDrawCreate(258.666656, 154.311157, "ROYAL GAMING");
TextDrawLetterSize(Textdraw1, 0.449999, 1.600000);
TextDrawAlignment(Textdraw1, 1);
TextDrawColor(Textdraw1, -1);
TextDrawSetShadow(Textdraw1, 0);
TextDrawSetOutline(Textdraw1, 0);
TextDrawBackgroundColor(Textdraw1, -16776961);
TextDrawFont(Textdraw1, 1);
TextDrawSetProportional(Textdraw1, 1);

Textdraw2 = TextDrawCreate(259.333251, 165.511123, "LOADING SCREEN ...");
TextDrawLetterSize(Textdraw2, 0.349333, 1.334518);
TextDrawAlignment(Textdraw2, 1);
TextDrawColor(Textdraw2, -1);
TextDrawSetShadow(Textdraw2, 0);
TextDrawSetOutline(Textdraw2, 1);
TextDrawBackgroundColor(Textdraw2, 255);
TextDrawFont(Textdraw2, 1);
TextDrawSetProportional(Textdraw2, 1);

Textdraw3 = TextDrawCreate(258.000000, 180.029632, "LD_SPAC:white");
TextDrawLetterSize(Textdraw3, 0.000000, 0.000000);
TextDrawTextSize(Textdraw3, 123.333343, 12.859252);
TextDrawAlignment(Textdraw3, 1);
TextDrawColor(Textdraw3, 252645375);
TextDrawSetShadow(Textdraw3, 0);
TextDrawSetOutline(Textdraw3, 0);
TextDrawFont(Textdraw3, 4);

Textdraw4 = TextDrawCreate(258.000000, 180.029632, "LD_SPAC:white");
TextDrawLetterSize(Textdraw4, 0.000000, 0.000000);
TextDrawTextSize(Textdraw4, 65.000000, 12.859252);
TextDrawAlignment(Textdraw4, 1);
TextDrawColor(Textdraw4, -1);
TextDrawSetShadow(Textdraw4, 0);
TextDrawSetOutline(Textdraw4, 0);
TextDrawFont(Textdraw4, 4);

Textdraw5 = TextDrawCreate(340.333312, 181.274078, "54%");
TextDrawLetterSize(Textdraw5, 0.264333, 0.903110);
TextDrawAlignment(Textdraw5, 1);
TextDrawColor(Textdraw5, -1);
TextDrawSetShadow(Textdraw5, 0);
TextDrawSetOutline(Textdraw5, 0);
TextDrawBackgroundColor(Textdraw5, 255);
TextDrawFont(Textdraw5, 2);
TextDrawSetProportional(Textdraw5, 1);

Textdraw6 = TextDrawCreate(353.999969, 121.540748, "LD_SPAC:white");
TextDrawLetterSize(Textdraw6, -0.003000, 0.136888);
TextDrawTextSize(Textdraw6, 67.000015, 50.192600);
TextDrawAlignment(Textdraw6, 1);
TextDrawColor(Textdraw6, -1);
TextDrawUseBox(Textdraw6, true);
TextDrawBoxColor(Textdraw6, 0);
TextDrawSetShadow(Textdraw6, 0);
TextDrawSetOutline(Textdraw6, 0);
TextDrawFont(Textdraw6, 5);
TextDrawSetPreviewModel(Textdraw6, 411);
TextDrawSetPreviewRot(Textdraw6, 0.000000, 0.000000, -20.000000, 1.000000);

Textdraw7 = TextDrawCreate(344.000000, 122.370368, "LD_SPAC:white");
TextDrawLetterSize(Textdraw7, 0.003000, 0.215703);
TextDrawTextSize(Textdraw7, 33.333324, 31.940746);
TextDrawAlignment(Textdraw7, 1);
TextDrawColor(Textdraw7, -1);
TextDrawUseBox(Textdraw7, true);
TextDrawBoxColor(Textdraw7, 0);
TextDrawSetShadow(Textdraw7, 0);
TextDrawSetOutline(Textdraw7, 0);
TextDrawFont(Textdraw7, 5);
TextDrawSetPreviewModel(Textdraw7, 294);
TextDrawSetPreviewRot(Textdraw7, 0.000000, 0.000000, -20.000000, 1.000000);

Textdraw8 = TextDrawCreate(216.666687, 124.444427, "LD_SPAC:white");
TextDrawLetterSize(Textdraw8, -0.007000, 0.211555);
TextDrawTextSize(Textdraw8, 51.333343, 48.118522);
TextDrawAlignment(Textdraw8, 1);
TextDrawColor(Textdraw8, -1);
TextDrawUseBox(Textdraw8, true);
TextDrawBoxColor(Textdraw8, 0);
TextDrawSetShadow(Textdraw8, 0);
TextDrawSetOutline(Textdraw8, 0);
TextDrawFont(Textdraw8, 5);
TextDrawSetPreviewModel(Textdraw8, 415);
TextDrawSetPreviewRot(Textdraw8, 0.000000, 0.000000, 20.000000, 1.000000);

Textdraw9 = TextDrawCreate(249.000030, 122.370368, "LD_SPAC:white");
TextDrawLetterSize(Textdraw9, -0.015666, 2.735703);
TextDrawTextSize(Textdraw9, 31.000000, 33.599998);
TextDrawAlignment(Textdraw9, 1);
TextDrawColor(Textdraw9, -1);
TextDrawUseBox(Textdraw9, true);
TextDrawBoxColor(Textdraw9, 0);
TextDrawSetShadow(Textdraw9, 0);
TextDrawSetOutline(Textdraw9, 0);
TextDrawFont(Textdraw9, 5);
TextDrawSetPreviewModel(Textdraw9, 292);
TextDrawSetPreviewRot(Textdraw9, 0.000000, 0.000000, 20.000000, 1.000000);

Textdraw10 = TextDrawCreate(288.999877, 194.548126, "Sacekajte malo...");
TextDrawLetterSize(Textdraw10, 0.208999, 0.757925);
TextDrawAlignment(Textdraw10, 1);
TextDrawColor(Textdraw10, -1);
TextDrawSetShadow(Textdraw10, 0);
TextDrawSetOutline(Textdraw10, 0);
TextDrawBackgroundColor(Textdraw10, -16776961);
TextDrawFont(Textdraw10, 1);
TextDrawSetProportional(Textdraw10, 1);

Textdraw11 = TextDrawCreate(18.333333, 13.274073, "LD_SPAC:white");
TextDrawLetterSize(Textdraw11, 0.000000, 0.000000);
TextDrawTextSize(Textdraw11, 28.333330, 26.133331);
TextDrawAlignment(Textdraw11, 1);
TextDrawColor(Textdraw11, 252645375);
TextDrawSetShadow(Textdraw11, 0);
TextDrawSetOutline(Textdraw11, 0);
TextDrawFont(Textdraw11, 4);

Textdraw12 = TextDrawCreate(46.666664, 42.311111, "LD_SPAC:white");
TextDrawLetterSize(Textdraw12, 0.000000, 0.000000);
TextDrawTextSize(Textdraw12, 28.666671, 25.718513);
TextDrawAlignment(Textdraw12, 1);
TextDrawColor(Textdraw12, -1);
TextDrawSetShadow(Textdraw12, 0);
TextDrawSetOutline(Textdraw12, 0);
TextDrawFont(Textdraw12, 4);

Textdraw13 = TextDrawCreate(75.666664, 71.348144, "LD_SPAC:white");
TextDrawLetterSize(Textdraw13, 0.000000, 0.000000);
TextDrawTextSize(Textdraw13, 31.333335, 25.303710);
TextDrawAlignment(Textdraw13, 1);
TextDrawColor(Textdraw13, 252645375);
TextDrawSetShadow(Textdraw13, 0);
TextDrawSetOutline(Textdraw13, 0);
TextDrawFont(Textdraw13, 4);

Textdraw14 = TextDrawCreate(107.333335, 99.140739, "LD_SPAC:white");
TextDrawLetterSize(Textdraw14, 0.000000, 0.000000);
TextDrawTextSize(Textdraw14, 30.333320, 26.548149);
TextDrawAlignment(Textdraw14, 1);
TextDrawColor(Textdraw14, -1);
TextDrawSetShadow(Textdraw14, 0);
TextDrawSetOutline(Textdraw14, 0);
TextDrawFont(Textdraw14, 4);

Textdraw15 = TextDrawCreate(138.000000, 129.422225, "LD_SPAC:white");
TextDrawLetterSize(Textdraw15, 0.000000, 0.000000);
TextDrawTextSize(Textdraw15, 33.333328, 28.622222);
TextDrawAlignment(Textdraw15, 1);
TextDrawColor(Textdraw15, 252645375);
TextDrawUseBox(Textdraw15, true);
TextDrawBoxColor(Textdraw15, 102);
TextDrawSetShadow(Textdraw15, 0);
TextDrawSetOutline(Textdraw15, 0);
TextDrawFont(Textdraw15, 4);

Textdraw16 = TextDrawCreate(171.333328, 163.437042, "LD_SPAC:white");
TextDrawLetterSize(Textdraw16, 0.000000, 0.000000);
TextDrawTextSize(Textdraw16, 33.666671, 30.696289);
TextDrawAlignment(Textdraw16, 1);
TextDrawColor(Textdraw16, -1);
TextDrawSetShadow(Textdraw16, 0);
TextDrawSetOutline(Textdraw16, 0);
TextDrawFont(Textdraw16, 4);

Textdraw17 = TextDrawCreate(588.666625, 13.688888, "LD_SPAC:white");
TextDrawLetterSize(Textdraw17, 0.000000, 0.000000);
TextDrawTextSize(Textdraw17, 34.000061, 30.696296);
TextDrawAlignment(Textdraw17, 1);
TextDrawColor(Textdraw17, 252645375);
TextDrawSetShadow(Textdraw17, 0);
TextDrawSetOutline(Textdraw17, 0);
TextDrawFont(Textdraw17, 4);

Textdraw18 = TextDrawCreate(553.666625, 47.288890, "LD_SPAC:white");
TextDrawLetterSize(Textdraw18, 0.000000, 0.000000);
TextDrawTextSize(Textdraw18, 31.000061, 32.355556);
TextDrawAlignment(Textdraw18, 1);
TextDrawColor(Textdraw18, -1);
TextDrawSetShadow(Textdraw18, 0);
TextDrawSetOutline(Textdraw18, 0);
TextDrawFont(Textdraw18, 4);
TextDrawSetPreviewModel(Textdraw18, 0);
TextDrawSetPreviewRot(Textdraw18, 0.000000, 0.000000, 0.000000, 0.000000);

Textdraw19 = TextDrawCreate(510.333312, 86.281478, "LD_SPAC:white");
TextDrawLetterSize(Textdraw19, 0.000000, 0.000000);
TextDrawTextSize(Textdraw19, 37.333374, 32.770378);
TextDrawAlignment(Textdraw19, 1);
TextDrawColor(Textdraw19, 252645375);
TextDrawSetShadow(Textdraw19, 0);
TextDrawSetOutline(Textdraw19, 0);
TextDrawFont(Textdraw19, 4);

Textdraw20 = TextDrawCreate(468.000000, 121.540740, "LD_SPAC:white");
TextDrawLetterSize(Textdraw20, 0.000000, 0.000000);
TextDrawTextSize(Textdraw20, 38.000000, 34.429626);
TextDrawAlignment(Textdraw20, 1);
TextDrawColor(Textdraw20, -1);
TextDrawSetShadow(Textdraw20, 0);
TextDrawSetOutline(Textdraw20, 0);
TextDrawFont(Textdraw20, 4);
TextDrawSetPreviewModel(Textdraw20, 0);
TextDrawSetPreviewRot(Textdraw20, 0.000000, 0.000000, 0.000000, 0.000000);

Textdraw21 = TextDrawCreate(421.000000, 156.385177, "LD_SPAC:white");
TextDrawLetterSize(Textdraw21, 0.000000, 0.000000);
TextDrawTextSize(Textdraw21, 40.666687, 37.333343);
TextDrawAlignment(Textdraw21, 1);
TextDrawColor(Textdraw21, 252645375);
TextDrawSetShadow(Textdraw21, 0);
TextDrawSetOutline(Textdraw21, 0);
TextDrawFont(Textdraw21, 4);

Textdraw22 = TextDrawCreate(5.666666, 222.340728, "LD_SPAC:white");
TextDrawLetterSize(Textdraw22, 0.000000, 0.000000);
TextDrawTextSize(Textdraw22, 31.000001, 29.451873);
TextDrawAlignment(Textdraw22, 1);
TextDrawColor(Textdraw22, 252645375);
TextDrawSetShadow(Textdraw22, 0);
TextDrawSetOutline(Textdraw22, 0);
TextDrawFont(Textdraw22, 4);

Textdraw23 = TextDrawCreate(39.666667, 222.755554, "LD_SPAC:white");
TextDrawLetterSize(Textdraw23, 0.000000, 0.000000);
TextDrawTextSize(Textdraw23, 29.666667, 29.451843);
TextDrawAlignment(Textdraw23, 1);
TextDrawColor(Textdraw23, -1);
TextDrawSetShadow(Textdraw23, 0);
TextDrawSetOutline(Textdraw23, 0);
TextDrawFont(Textdraw23, 4);

Textdraw24 = TextDrawCreate(74.333335, 222.755554, "LD_SPAC:white");
TextDrawLetterSize(Textdraw24, 0.000000, 0.000000);
TextDrawTextSize(Textdraw24, 26.333328, 29.451843);
TextDrawAlignment(Textdraw24, 1);
TextDrawColor(Textdraw24, 252645375);
TextDrawSetShadow(Textdraw24, 0);
TextDrawSetOutline(Textdraw24, 0);
TextDrawFont(Textdraw24, 4);

Textdraw25 = TextDrawCreate(105.333335, 222.340728, "LD_SPAC:white");
TextDrawLetterSize(Textdraw25, 0.000000, 0.000000);
TextDrawTextSize(Textdraw25, 25.000007, 29.866668);
TextDrawAlignment(Textdraw25, 1);
TextDrawColor(Textdraw25, -1);
TextDrawSetShadow(Textdraw25, 0);
TextDrawSetOutline(Textdraw25, 0);
TextDrawFont(Textdraw25, 4);

Textdraw26 = TextDrawCreate(134.333328, 221.511108, "LD_SPAC:white");
TextDrawLetterSize(Textdraw26, 0.000000, 0.000000);
TextDrawTextSize(Textdraw26, 28.666671, 31.111114);
TextDrawAlignment(Textdraw26, 1);
TextDrawColor(Textdraw26, 252645375);
TextDrawSetShadow(Textdraw26, 0);
TextDrawSetOutline(Textdraw26, 0);
TextDrawFont(Textdraw26, 4);
TextDrawSetPreviewModel(Textdraw26, 560);
TextDrawSetPreviewRot(Textdraw26, 0.000000, 0.000000, -20.000000, 1.000000);

Textdraw27 = TextDrawCreate(166.000000, 221.511108, "LD_SPAC:white");
TextDrawLetterSize(Textdraw27, 0.000000, 0.000000);
TextDrawTextSize(Textdraw27, 29.333328, 31.111114);
TextDrawAlignment(Textdraw27, 1);
TextDrawColor(Textdraw27, -1);
TextDrawSetShadow(Textdraw27, 0);
TextDrawSetOutline(Textdraw27, 0);
TextDrawFont(Textdraw27, 4);

Textdraw28 = TextDrawCreate(200.000000, 221.511108, "LD_SPAC:white");
TextDrawLetterSize(Textdraw28, 0.000000, 0.000000);
TextDrawTextSize(Textdraw28, 30.666671, 31.525924);
TextDrawAlignment(Textdraw28, 1);
TextDrawColor(Textdraw28, 252645375);
TextDrawSetShadow(Textdraw28, 0);
TextDrawSetOutline(Textdraw28, 0);
TextDrawFont(Textdraw28, 4);

Textdraw29 = TextDrawCreate(234.666671, 221.511108, "LD_SPAC:white");
TextDrawLetterSize(Textdraw29, 0.000000, 0.000000);
TextDrawTextSize(Textdraw29, 26.666671, 31.111114);
TextDrawAlignment(Textdraw29, 1);
TextDrawColor(Textdraw29, -1);
TextDrawSetShadow(Textdraw29, 0);
TextDrawSetOutline(Textdraw29, 0);
TextDrawFont(Textdraw29, 4);

Textdraw30 = TextDrawCreate(265.333312, 221.925918, "LD_SPAC:white");
TextDrawLetterSize(Textdraw30, 0.000000, 0.000000);
TextDrawTextSize(Textdraw30, 28.333343, 30.696304);
TextDrawAlignment(Textdraw30, 1);
TextDrawColor(Textdraw30, 252645375);
TextDrawSetShadow(Textdraw30, 0);
TextDrawSetOutline(Textdraw30, 0);
TextDrawFont(Textdraw30, 4);

Textdraw31 = TextDrawCreate(297.000000, 221.511108, "LD_SPAC:white");
TextDrawLetterSize(Textdraw31, 0.000000, 0.000000);
TextDrawTextSize(Textdraw31, 25.666656, 31.525924);
TextDrawAlignment(Textdraw31, 1);
TextDrawColor(Textdraw31, -1);
TextDrawSetShadow(Textdraw31, 0);
TextDrawSetOutline(Textdraw31, 0);
TextDrawFont(Textdraw31, 4);

Textdraw32 = TextDrawCreate(326.666687, 221.925918, "LD_SPAC:white");
TextDrawLetterSize(Textdraw32, 0.000000, 0.000000);
TextDrawTextSize(Textdraw32, 28.999969, 31.940750);
TextDrawAlignment(Textdraw32, 1);
TextDrawColor(Textdraw32, 252645375);
TextDrawSetShadow(Textdraw32, 0);
TextDrawSetOutline(Textdraw32, 0);
TextDrawFont(Textdraw32, 4);

Textdraw33 = TextDrawCreate(360.000000, 220.266662, "LD_SPAC:white");
TextDrawLetterSize(Textdraw33, 0.000000, 0.000000);
TextDrawTextSize(Textdraw33, 31.666687, 34.014831);
TextDrawAlignment(Textdraw33, 1);
TextDrawColor(Textdraw33, -1);
TextDrawSetShadow(Textdraw33, 0);
TextDrawSetOutline(Textdraw33, 0);
TextDrawFont(Textdraw33, 4);

Textdraw34 = TextDrawCreate(395.666656, 219.022216, "LD_SPAC:white");
TextDrawLetterSize(Textdraw34, 0.000000, 0.000000);
TextDrawTextSize(Textdraw34, 37.666656, 34.844451);
TextDrawAlignment(Textdraw34, 1);
TextDrawColor(Textdraw34, 252645375);
TextDrawSetShadow(Textdraw34, 0);
TextDrawSetOutline(Textdraw34, 0);
TextDrawFont(Textdraw34, 4);

Textdraw35 = TextDrawCreate(436.333343, 218.607406, "LD_SPAC:white");
TextDrawLetterSize(Textdraw35, 0.000000, 0.000000);
TextDrawTextSize(Textdraw35, 27.333312, 34.429626);
TextDrawAlignment(Textdraw35, 1);
TextDrawColor(Textdraw35, -1);
TextDrawSetShadow(Textdraw35, 0);
TextDrawSetOutline(Textdraw35, 0);
TextDrawFont(Textdraw35, 4);
TextDrawSetPreviewModel(Textdraw35, 0);
TextDrawSetPreviewRot(Textdraw35, 0.000000, 0.000000, 0.000000, 0.000000);

Textdraw36 = TextDrawCreate(466.333343, 220.681488, "LD_SPAC:white");
TextDrawLetterSize(Textdraw36, 0.000000, 0.000000);
TextDrawTextSize(Textdraw36, 31.666656, 31.940734);
TextDrawAlignment(Textdraw36, 1);
TextDrawColor(Textdraw36, 252645375);
TextDrawSetShadow(Textdraw36, 0);
TextDrawSetOutline(Textdraw36, 0);
TextDrawFont(Textdraw36, 4);

Textdraw37 = TextDrawCreate(500.000000, 217.777770, "LD_SPAC:white");
TextDrawLetterSize(Textdraw37, 0.000000, 0.000000);
TextDrawTextSize(Textdraw37, 34.000000, 35.674087);
TextDrawAlignment(Textdraw37, 1);
TextDrawColor(Textdraw37, -1);
TextDrawSetShadow(Textdraw37, 0);
TextDrawSetOutline(Textdraw37, 0);
TextDrawFont(Textdraw37, 4);

Textdraw38 = TextDrawCreate(536.666687, 219.437042, "LD_SPAC:white");
TextDrawLetterSize(Textdraw38, 0.000000, 0.000000);
TextDrawTextSize(Textdraw38, 31.666625, 33.185180);
TextDrawAlignment(Textdraw38, 1);
TextDrawColor(Textdraw38, 252645375);
TextDrawSetShadow(Textdraw38, 0);
TextDrawSetOutline(Textdraw38, 0);
TextDrawFont(Textdraw38, 4);

Textdraw39 = TextDrawCreate(572.333312, 220.266662, "LD_SPAC:white");
TextDrawLetterSize(Textdraw39, 0.000000, 0.000000);
TextDrawTextSize(Textdraw39, 29.333374, 33.185195);
TextDrawAlignment(Textdraw39, 1);
TextDrawColor(Textdraw39, -1);
TextDrawSetShadow(Textdraw39, 0);
TextDrawSetOutline(Textdraw39, 0);
TextDrawFont(Textdraw39, 4);

Textdraw40 = TextDrawCreate(604.666687, 217.362960, "LD_SPAC:white");
TextDrawLetterSize(Textdraw40, 0.000000, 0.000000);
TextDrawTextSize(Textdraw40, 30.666625, 37.333328);
TextDrawAlignment(Textdraw40, 1);
TextDrawColor(Textdraw40, 252645375);
TextDrawSetShadow(Textdraw40, 0);
TextDrawSetOutline(Textdraw40, 0);
TextDrawFont(Textdraw40, 4);

Textdraw41 = TextDrawCreate(0.000000, 234.785186, "LD_SPAC:white");
TextDrawLetterSize(Textdraw41, 0.000000, 0.000000);
TextDrawTextSize(Textdraw41, 640.000000, -1.659271);
TextDrawAlignment(Textdraw41, 1);
TextDrawColor(Textdraw41, 7602175);
TextDrawSetShadow(Textdraw41, 0);
TextDrawSetOutline(Textdraw41, 0);
TextDrawFont(Textdraw41, 4);

Textdraw42 = TextDrawCreate(1.000000, 238.933349, "LD_SPAC:white");
TextDrawLetterSize(Textdraw42, 0.000000, 0.000000);
TextDrawTextSize(Textdraw42, 639.000000, 1.659240);
TextDrawAlignment(Textdraw42, 1);
TextDrawColor(Textdraw42, 5111807);
TextDrawSetShadow(Textdraw42, 0);
TextDrawSetOutline(Textdraw42, 0);
TextDrawFont(Textdraw42, 4);
